# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170913_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalEducationalGameImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deg_authoring/images/')),
                ('digital_educational_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.DigitalEducationalGame')),
            ],
        ),
    ]
