# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_digitaleducationalgameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaleducationalgameimage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='digitaleducationalgameimage',
            name='image',
            field=models.ImageField(upload_to='deg_authoring/images/games/'),
        ),
    ]
