# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_featuredgame_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredgame',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
