# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170928_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
